# Generated by Django 4.2 on 2025-06-04 00:15

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('tecnico', 'Técnico')], default='tecnico', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LineaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_tipo', models.CharField(choices=[('linea', 'En línea de producción'), ('deposito', 'En depósito'), ('mantenimiento', 'En taller de mantenimiento')], default='linea', max_length=20)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('reparacion', 'En Reparación'), ('baja', 'Dado de Baja'), ('standby', 'En Espera')], default='operativo', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('horas_uso', models.PositiveIntegerField(default=0)),
                ('manual', models.FileField(blank=True, null=True, upload_to='manuales/')),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('potencia', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('rpm', models.CharField(max_length=50)),
                ('brida', models.CharField(max_length=50)),
                ('anclaje', models.CharField(max_length=50)),
                ('ref_plano', models.FileField(blank=True, null=True, upload_to='plano_motores/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='motores/')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motores_creados', to=settings.AUTH_USER_MODEL)),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deposito')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipo')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lineaproduccion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PLC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('siemens', 'Siemens'), ('allen_bradley', 'Allen-Bradley'), ('schneider', 'Schneider'), ('delta', 'Delta'), ('omron', 'Omron'), ('otros', 'Otros')], max_length=50)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('firmware', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('diagrama', models.FileField(blank=True, null=True, upload_to='diagramas_plc/')),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='PLCEntradaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('digital_in', 'Entrada Digital'), ('digital_out', 'Salida Digital'), ('analog_in', 'Entrada Analógica'), ('analog_out', 'Salida Analógica'), ('especial', 'Función Especial')], max_length=50)),
                ('etiqueta', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('valor_actual', models.CharField(blank=True, max_length=50)),
                ('rango', models.CharField(blank=True, max_length=100)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('historico', models.JSONField(blank=True, default=list)),
                ('plc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_salidas', to='api.plc')),
            ],
            options={
                'verbose_name': 'Entrada/Salida PLC',
                'verbose_name_plural': 'Entradas/Salidas PLC',
                'ordering': ['tipo', 'direccion'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(choices=[('electrico', 'Eléctrico'), ('mecanico', 'Mecánico'), ('electronico', 'Electrónico'), ('hidraulico', 'Hidráulico'), ('neumatico', 'Neumático'), ('general', 'General')], max_length=50)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectores', to='api.lineaproduccion')),
            ],
            options={
                'unique_together': {('nombre', 'linea')},
            },
        ),
        migrations.CreateModel(
            name='Variador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion_tipo', models.CharField(choices=[('linea', 'En línea de producción'), ('deposito', 'En depósito'), ('mantenimiento', 'En taller de mantenimiento')], default='linea', max_length=20)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('reparacion', 'En Reparación'), ('baja', 'Dado de Baja'), ('standby', 'En Espera')], default='operativo', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('horas_uso', models.PositiveIntegerField(default=0)),
                ('codigo', models.CharField(max_length=100, unique=True)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('potencia', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='variadores/')),
                ('manual', models.FileField(blank=True, null=True, upload_to='manuales_variadores/')),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variadores_creados', to=settings.AUTH_USER_MODEL)),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.deposito')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.equipo')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lineaproduccion')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_tipo', models.CharField(max_length=20)),
                ('equipo_id', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('correctivo', 'Correctivo'), ('preventivo', 'Preventivo'), ('predictivo', 'Predictivo'), ('modificacion', 'Modificación')], max_length=20)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='reparaciones/')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='PLCLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('configuracion', 'Cambio de Configuración'), ('valor', 'Cambio de Valor'), ('mantenimiento', 'Mantenimiento')], max_length=50)),
                ('valor_anterior', models.CharField(blank=True, max_length=100)),
                ('valor_nuevo', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entrada_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.plcentradasalida')),
                ('plc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plc')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo'), ('calibracion', 'Calibración')], default='correctivo', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('tiempo_estimado', models.PositiveIntegerField(blank=True, help_text='Tiempo estimado en minutos', null=True)),
                ('tiempo_real', models.PositiveIntegerField(blank=True, help_text='Tiempo real en minutos', null=True)),
                ('checklist', models.JSONField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('equipos', models.ManyToManyField(blank=True, to='api.motor')),
                ('operario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('variadores', models.ManyToManyField(blank=True, to='api.variador')),
            ],
        ),
        migrations.AddField(
            model_name='motor',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sector'),
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_tipo', models.CharField(max_length=20)),
                ('equipo_id', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_evento', models.CharField(choices=[('instalacion', 'Instalación'), ('reparacion', 'Reparación'), ('mantenimiento', 'Mantenimiento'), ('baja', 'Baja'), ('movimiento', 'Movimiento de ubicación')], max_length=50)),
                ('descripcion', models.TextField()),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ordenmantenimiento')),
                ('reparacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reparacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('motor', 'Motor'), ('variador', 'Variador'), ('orden', 'Orden de Mantenimiento'), ('reparacion', 'Reparación')], max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('objeto_id', models.IntegerField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='api.sector'),
        ),
        migrations.AddIndex(
            model_name='plclog',
            index=models.Index(fields=['plc', 'fecha'], name='api_plclog_plc_id_2ca308_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plcentradasalida',
            unique_together={('plc', 'direccion')},
        ),
        migrations.AlterUniqueTogether(
            name='equipo',
            unique_together={('nombre', 'sector')},
        ),
    ]
