# Generated by Django 4.2 on 2025-08-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('usuario_nombre', models.CharField(max_length=150)),
                ('token_fcm', models.CharField(max_length=255, unique=True)),
                ('plataforma', models.CharField(max_length=20)),
                ('version_app', models.CharField(blank=True, max_length=20)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_dispositivos',
            },
        ),
        migrations.CreateModel(
            name='NotificacionApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.IntegerField()),
                ('usuario_nombre', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('revision', 'Próxima Revisión'), ('inspeccion', 'Inspección Pendiente'), ('mantenimiento', 'Mantenimiento Programado'), ('alerta', 'Alerta de Equipo'), ('parada', 'Parada de Producción'), ('falla', 'Falla Detectada'), ('completado', 'Tarea Completada')], max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('data_adicional', models.JSONField(blank=True, default=dict)),
                ('relacion_id', models.IntegerField(blank=True, null=True)),
                ('relacion_tipo', models.CharField(blank=True, max_length=50)),
                ('enviada_push', models.BooleanField(default=False)),
                ('intentos_envio', models.IntegerField(default=0)),
                ('error_envio', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'app_notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='notificacionapp',
            index=models.Index(fields=['usuario_id', 'leida'], name='app_notific_usuario_19064e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionapp',
            index=models.Index(fields=['fecha_creacion'], name='app_notific_fecha_c_987ec1_idx'),
        ),
    ]
