# Generated by Django 4.2 on 2025-06-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenmantenimiento',
            name='motores',
            field=models.ManyToManyField(blank=True, to='api.motor'),
        ),
        migrations.AlterField(
            model_name='ordenmantenimiento',
            name='equipos',
            field=models.ManyToManyField(blank=True, to='api.equipo'),
        ),
    ]
