# Generated by Django 4.2 on 2025-06-25 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ordenmantenimiento_motores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambioOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('tipo_cambio', models.CharField(choices=[('descripcion', 'Descripción'), ('estado', 'Estado'), ('equipo', 'Equipo'), ('imagen', 'Imagen')], max_length=20)),
                ('campo_afectado', models.CharField(blank=True, max_length=50, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('equipo_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('equipo_id', models.PositiveIntegerField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='api.ordenmantenimiento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
