# Generated by Django 4.2.8 on 2025-09-15 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reuniondiaria_planificacionreunion_incidenciareunion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NodeRedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dato', models.CharField(choices=[('produccion', 'Producción'), ('falla', 'Falla'), ('parada', 'Parada')], max_length=20)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('estado', models.CharField(choices=[('exito', 'Éxito'), ('error', 'Error'), ('advertencia', 'Advertencia')], max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('registros_afectados', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-fecha_recepcion'],
                'indexes': [models.Index(fields=['fecha_recepcion', 'tipo_dato'], name='api_nodered_fecha_r_97c6d1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProduccionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('unidad', models.CharField(default='unidades', max_length=20)),
                ('meta_produccion', models.PositiveIntegerField(blank=True, null=True)),
                ('eficiencia', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fuente_dato', models.CharField(default='node_red', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lineaproduccion')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turno')),
            ],
            options={
                'verbose_name_plural': 'Producción por turnos',
                'indexes': [models.Index(fields=['fecha', 'linea'], name='api_producc_fecha_030b7a_idx')],
                'unique_together': {('fecha', 'turno', 'linea')},
            },
        ),
        migrations.CreateModel(
            name='ParadaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('limpieza', 'Limpieza'), ('cambio_linea', 'Cambio de Línea'), ('falta_material', 'Falta de Material'), ('falla_equipo', 'Falla de Equipo'), ('programacion', 'Cambio de Programación'), ('calidad', 'Problema de Calidad'), ('personal', 'Falta de Personal')], max_length=20)),
                ('tipo', models.CharField(choices=[('programada', 'Programada'), ('no_programada', 'No Programada')], default='no_programada', max_length=20)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fuente_dato', models.CharField(default='node_red', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lineaproduccion')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turno')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'linea'], name='api_paradat_fecha_7b46c0_idx'), models.Index(fields=['equipo', 'fecha'], name='api_paradat_equipo__031802_idx')],
            },
        ),
        migrations.CreateModel(
            name='FallaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('electrica', 'Eléctrica'), ('mecanica', 'Mecánica'), ('instrumentacion', 'Instrumentación'), ('proceso', 'Proceso'), ('calidad', 'Calidad'), ('operativa', 'Operativa')], max_length=20)),
                ('gravedad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave'), ('critica', 'Crítica')], default='moderada', max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('duracion_minutos', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('accion_correctiva', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fuente_dato', models.CharField(default='node_red', max_length=20)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.equipo')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lineaproduccion')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turno')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha', 'linea'], name='api_fallatu_fecha_63568f_idx'), models.Index(fields=['equipo', 'fecha'], name='api_fallatu_equipo__2b3301_idx')],
            },
        ),
    ]
