# Generated by Django 4.2 on 2025-07-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_historialcambioorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='motor',
            name='plano_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
