# Generated by Django 4.2 on 2025-07-08 01:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_motor_imagen_url_motor_plano_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reparacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
