# Generated by Django 4.2.8 on 2025-09-25 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_turno_noderedlog_produccionturno_paradaturno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('producto', models.CharField(blank=True, max_length=100)),
                ('bandejas', models.PositiveIntegerField(blank=True, null=True)),
                ('fabricacion_toneladas', models.FloatField(blank=True, null=True)),
                ('fabricacion_scrap', models.FloatField(blank=True, null=True)),
                ('apilado_vagones', models.PositiveIntegerField(blank=True, null=True)),
                ('apilado_toneladas', models.FloatField(blank=True, null=True)),
                ('coccion_vagones', models.PositiveIntegerField(blank=True, null=True)),
                ('coccion_toneladas', models.FloatField(blank=True, null=True)),
                ('desapilado_primera', models.PositiveIntegerField(blank=True, null=True)),
                ('desapilado_segunda', models.PositiveIntegerField(blank=True, null=True)),
                ('desapilado_toneladas', models.FloatField(blank=True, null=True)),
                ('meta_produccion', models.PositiveIntegerField(blank=True, null=True)),
                ('eficiencia', models.FloatField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fuente_dato', models.CharField(default='node_red', max_length=20)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lineaproduccion')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turno')),
            ],
            options={
                'verbose_name_plural': 'Producción por turnos',
                'indexes': [models.Index(fields=['fecha', 'linea'], name='api_producc_fecha_5e08c8_idx')],
                'unique_together': {('fecha', 'turno', 'linea')},
            },
        ),
    ]
