# Generated by Django 4.2 on 2025-07-08 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reparacion_created_at_reparacion_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspeccionEjecucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RutaInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo_tipo', models.CharField(max_length=50)),
                ('activo_id', models.IntegerField()),
                ('frecuencia_dias', models.PositiveIntegerField(help_text='Cada cuántos días debe repetirse')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VariableInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=50)),
                ('valor_referencia', models.FloatField()),
                ('tolerancia', models.FloatField(help_text='Rango permitido (+/-)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='api.rutainspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoInspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_medido', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='api.inspeccionejecucion')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.variableinspeccion')),
            ],
        ),
        migrations.AddField(
            model_name='inspeccionejecucion',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='api.rutainspeccion'),
        ),
        migrations.AddField(
            model_name='inspeccionejecucion',
            name='tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
