import openpyxl
from openpyxl.styles import Font

# Lista de equipos (eliminando duplicados y "Equipo por defecto")
equipos = [
    "Pinza Apilado (Subir/Bajar)",
    "Azzeramento LP1 MADRE VITE",
    "Azzeramento LP2 MADRE VITE",
    "LATERAL GV LP1",
    "LATERAL PV LP1",
    "LATERAL GV LP2",
    "LATERAL PV LP2",
    "Azzeramento LS1 MADRE VITE",
    "Azzeramento LS2 MADRE VITE",
    "LATERAL GV LS1",
    "LATERAL PV LS1",
    "LATERAL GV LS2",
    "LATERAL PV LS2",
    "Ventilación forzada cajón primario (NO HAY)",
    "Ventilación forzada cajón secundario (NO HAY)",
    "ALIMENTACIÓN RECTIF GV LP1",
    "ALIMENTACIÓN RECTIF PV LP1",
    "ALIMENTACIÓN RECTIF GV LP2",
    "ALIMENTACIÓN RECTIF PV LP2",
    "ALIMENTACIÓN RECTIF GV LS1",
    "ALIMENTACIÓN RECTIF PV LS1",
    "ALIMENTACIÓN RECTIF GV LS2",
    "ALIMENTACIÓN RECTIF PV LS2",
    "VENTILADOR CAJÓN ARCILLA",
    "Motor TRASLACIÓN cinta LANZADERA",
    "MOTOR Nº1 (Lado L1) Traslación CARRO puente",
    "MOTOR Nº2 (Lado L2) Traslación CARRO puente",
    "MOTOR Nº1 (Lado pasarela) Traslación puente",
    "MOTOR Nº2 (Lado norte) Traslación puente",
    "VENTILADOR DE BOMBA DE ACEITE",
    "BOMBA ACEITE",
    "REPARTIDOR CINTA TP7",
    "REPARTIDOR CINTA TP8",
    "REPARTIDOR CINTA TP9",
    "REPARTIDOR CINTA TP10",
    "CINTA TP2A",
    "CAJÓN ARCILLA",
    "CINTA TP22",
    "ASPO CAJÓN ARCILLA",
    "CINTA TP23.0",
    "Aspos cajón Secundario",
    "CENTRAL HIDRÁULICA LS1",
    "CENTRAL HIDRÁULICA LS2",
    "CINTA TP23.1",
    "CINTA TP23.2",
    "CINTA TP24",
    "CINTA TP24A",
    "CINTA TP19",
    "BOMBA DE AGUA",
    "CINTA TP5",
    "CINTA TP6",
    "Cajón dosificador secundario",
    "CINTA TP3",
    "CINTA TP4",
    "CINTA TP7",
    "CINTA TP8",
    "CENTRAL HIDRÁULICA LP1",
    "CENTRAL HIDRÁULICA LP2",
    "CINTA TP9",
    "CINTA TP11",
    "CINTA TP10",
    "CINTA TP20",
    "MOTOR C.H MOVIMIENTO BRAZO",
    "CINTA TP18",
    "CINTA TP16",
    "CINTA TP1",
    "CINTA TP17",
    "CINTA TP15",
    "CINTA TP2",
    "CINTA TP13",
    "CINTA TP12",
    "CINTA TP21",
    "CINTA TP 14",
    "Aspos cajón Primario (OJO está en fase partida)",
    "MOTOR Nº1 ROTACIÓN TAZAS (Lado Norte)",
    "MOTOR Nº2  ROTACIÓN TAZAS (Lado Pasarela)",
    "Cajón dosificador principal",
    "PV LP2",
    "PV LP1",
    "PV LS1",
    "PV LS2",
    "GV LP2",
    "GV LP1",
    "GV LS1",
    "GV LS2",
    "Vent. Carro 3",
    "TR1 Traslación L/Horno",
    "TR1 Traslación L/Viales",
    "TR2 Traslación L/Horno",
    "TR2 Traslación L/Acopio",
    "Cinta pulmón nº1",
    "Cinta pulmón nº2",
    "Cinta pulmón nº3",
    "Rotación pinza giro",
    "Cadena alimentador",
    "CINTA T7",
    "Elevacíon rodillos P/E",
    "Rodillos plat salida",
    "Cadenas grupo nº3",
    "Cadena programación 1",
    "Cadena programación 2",
    "Cinta bajo Pinza giro",
    "Ch4",
    "Ch5",
    "Ch1 (Alta/Bajavelocidad)",
    "TD1(traslación)",
    "Cinta 1",
    "Cinta 2",
    "Aire comb. Rción nº2",
    "Pala programación",
    "Cadena nº2",
    "Traslación Transp.palets",
    "Cortador de barra",
    "Corte nº1",
    "Corte nº2",
    "Cinta pulmón 1",
    "Cinta pulmón 2",
    "Cinta aceleración",
    "Rodillos plat entrada",
    "Cadenas grupo nº2",
    "Rotación plastificadora",
    "Cinta bajo Pinza APILADO",
    "Traslación P DESAPILADO",
    "Traslación pinza APILADO",
    "Cadena nº1",
    "Cadena plastificado",
    "Trasl. P Recomposición",
    "Cadena mojado",
    "CINTA T13",
    "Cinta Cajón tierra",
    "REPARTIDOR CINTA T13",
    "TD1",
    "TD4",
    "Rodillos multihueco",
    "Correas plat entrada",
    "bandeja",
    "Aire comb. Rción nº1",
    "Cadenas plat salida",
    "C.H DESAPILADO",
    "Pta 0",
    "Pta 1",
    "Pta 2",
    "Pta 3",
    "Pta 3A",
    "Pta 3B",
    "Pta 4",
    "Elevacíon Transp.palets",
    "CINTA T9",
    "CINTA T8",
    "CINTA T12",
    "CINTA T15",
    "CINTA T16",
    "CINTA TD0",
    "CINTA TD2",
    "Pala",
    "Izaje pinza giro",
    "Ch2",
    "Ch3",
    "Duplicador pallets",
    "Extractor de polvo",
    "CINTA T4A",
    "CINTA T4B (NO OPERA)",
    "Cavador Cajón tierra",
    "Correas plat salida",
    "Aire comb Rdo",
    "Soplador",
    "TR1 C.H",
    "C.H APILADO",
    "Enfriamiento de humos",
    "C.H Pinza DESAPILADO",
    "C.H P. Recomposición",
    "T14",
    "TD3",
    "Soplado b/Vagones 1",
    "Soplado b/Vagones 2",
    "Enfriamiento rápido",
    "Izaje P. DESAPILADO",
    "TR2 C.H",
    "CINTA T10 (NO OPERA)",
    "C.H Horno",
    "Bomba vacío nº1",
    "Bomba vacío nº2",
    "trozador DESCARTE",
    "Movimiento estanterías",
    "Extracción b/vagones",
    "Extracción pre-horno",
    "Rción nº1 Túnel espera",
    "Rción nº2 Túnel espera",
    "Compresor 1",
    "Compresor 2",
    "Extracción nº1",
    "Extracción nº2",
    "Extracción nº3",
    "Extracción nº4",
    "Extracción nº5",
    "Recirculación nº1",
    "Sobre presión",
    "Principal nº1",
    "Principal nº2",
    "Recirculación nº2",
    "Aspiración",
    "Tiro nº1",
    "Tiro nº2",
    "Aire combustión",
    "Recuperación",
    "Amasadora filtro",
    "PV BSF11.11",
    "GV BSF11.11",
    "Amasadora",
    "Reciclado nº1",
    "Reciclado nº2",
    "Extrusora",
    "CINTA T4 C",
    "CINTA T5",
    "CINTA T6",
    "Rectificado PV",
    "Rectificado GV",
    "Ch6",
    "Cadena mesa giro",
    "Giro mesa de giro",
    "Cadena nº3",
    "Elevacíon film",
    "Traslación",
    "Compresor 3",
    "T1 (NO OPERA)",
    "T2 (NO OPERA)",
    "PO Barredora",
    "VENTILADOR 1",
    "VENTILADOR 4",
    "VENTILADOR 5",
    "VENTILADOR 6",
    "VENTILADOR 15",
    "VENTILADOR 2",
    "VENTILADOR 3",
    "Pinza APILADO cabezal 1",
    "Pinza APILADO cabezal 2",
    "Pinza APILADO cabezal 3",
    "Cadenas grupo 6",
    "Cadenas programación",
    "Pinza APILADO Elev. GV",
    "Elevacíon asc descarga",
    "Pte grua Elevacíon",
    "Bco desvío lad.Elevacíon",
    "Cinta B/Pinza de APILADO",
    "Cabrestante via 2",
    "Cadenas asc descarga",
    "Lanzadera asc descarga",
    "Banco cadena salida 1",
    "Banco cadena salida 3",
    "Bco desvío Band vacías",
    "Cadena acum. Band. Vacias",
    "Cadenas grupo 4",
    "Cadenas grupo 5",
    "Bco desvío lad. Cadenas",
    "Bco desvío lad.Traslación",
    "Banco cadena salida 2",
    "Cadenas grupo1",
    "Cadenas grupo2",
    "Cadenas grupo3",
    "Cadenas 3A",
    "Pinza APILADO traslación",
    "Pte grua traslación carro",
    "Giro Rodillos",
    "Rodillos compactación 1",
    "Rodillos compactación 2",
    "Pte grua traslación L/S",
    "Pte grua traslación L/H",
    "Pza DESAPILADO cabezal 1",
    "Pza DESAPILADO cabezal 2",
    "Pinza elevacion",
    "Pza DESAPILADO traslación",
    "Pinza elevacion backup",
    "Cadenas de salida 1",
    "Cadenas de salida 2",
    "Cadenas de salida 3",
    "Cadenas de salida 4",
    "Cadenas de salida 5",
    "Cadenas de salida 6",
    "Cadenas de salida 7",
    "Cadena 8",
    "Plastificadora Giro",
    "Alimentador de Pallets",
    "Mesa de rodillos ENTRADA",
    "Mesa de rodillos SALIDA",
    "Rodillos paquete completo",
    "Rodillos Plastificado",
    "Rodillos pre Giro",
    "Plastificadora Elevacíon",
    "Traslación TRES",
    "CH 1",
    "CH 2",
    "C.H PO1",
    "C.H PO2",
    "C-H TRES",
    "C-H TRSS",
    "Traslación TRSS",
    "VENTILADOR 7",
    "VENTILADOR 8",
    "VENTILADOR 9",
    "VENTILADOR 10",
    "VENTILADOR 11",
    "VENTILADOR 12",
    "VENTILADOR 13",
    "VENTILADOR 14",
    "VENTILADOR 16",
    "VENTILADOR 17",
    "VENTILADOR 18",
    "VENTILADOR 19",
    "VENTILADOR 20",
    "VENTILADOR 21",
    "VENTILADOR 22",
    "VENTILADOR 23",
    "VENTILADOR 24",
    "VENTILADOR 25",
    "VENTILADOR 26",
    "VENTILADOR 27",
    "VENTILADOR 28",
    "Rodillos plat entrada giro",
    "Cinta transferencia",
    "Cortador de barra",
    "Cinta Expulcion cort. Barra",
    "Rodillos plat transferencia",
    "Plat salida rodillos",
    "Cadenas pulmón 2",
    "Cadenas pulmón 3",
    "Cinta recorte multihueco",
    "Correas plat transferencia",
    "Cadenas pulmón 4",
    "Elevacíon asc carga",
    "Plat salida cadenas",
    "Cadenas Bco desv ban LL",
    "Bco cadenas entrada 1",
    "Bco cadenas entrada 2",
    "Cadenas pulmón 1",
    "Cadenas asc carga",
    "Lanzadera asc carga",
    "TD2",
    "Corte nº1",
    "Ventilador Foso 1",
    "Ventilador Foso 2",
    "Ventilador Qs Laterales",
    "Vent enfriamiento rápido",
    "Ventilador Qs Verticales",
    "Ventilador Recirculador",
    "Ventilador contravento",
    "Ventilador Tiro N°1",
    "Ventilador Tiro N°2",
    "Ventilador recuperación",
    "Cinta desmenuzador",
    "T30",
    "T32",
    "T34",
    "T33",
    "PV Bedeschi",
    "T31",
    "T35",
    "GV Bedeschi",
    "Pta 1 Horno",
    "Pta 2 Horno",
    "Pta 3 Horno",
    "Pta 4 Horno",
    "Carro TRS-Desap",
    "Carro Desap-Api",
    "Carro Api-TRE",
    "PO DESAPILADO",
    "PO APILADO",
    "PO Salida",
    "TR Entrada Traslación",
    "TR Salida Traslación",
    "TR Entrada C.H",
    "PO Horno",
    "TR Salida C.H",
    "Extracción 1 OMEGA",
    "Extracción 2 OMEGA",
    "Quemador",
    "BT 1",
    "BT 2",
    "AT 1",
    "AT 2"
]

# Eliminar duplicados exactos (conservando el orden)
equipos_unicos = []
vistos = set()
for equipo in equipos:
    if equipo not in vistos:
        equipos_unicos.append(equipo)
        vistos.add(equipo)

# Crear un nuevo libro de Excel
wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Equipos"

# Encabezados
ws['A1'] = "id"
ws['B1'] = "nombre"
ws['C1'] = "linea_id"

# Estilo para encabezados
for cell in ws[1]:
    cell.font = Font(bold=True)

# Llenar datos
for i, equipo in enumerate(equipos_unicos, start=1):
    ws.append([i, equipo, 1])  # linea_id = 1 para todos

# Guardar el archivo
wb.save("equipos1.xlsx")
print(f"Archivo 'equipos.xlsx' generado exitosamente con {len(equipos_unicos)} equipos únicos.")