from .admin_site import AutoTaskAdminSite
from .models import *
from .admin_config import *

# Crear la instancia del admin personalizado
custom_admin_site = AutoTaskAdminSite(name='autotask_admin')

# Registrar todos los modelos con sus 
#custom_admin_site.register(User, CustomUserAdmin)
custom_admin_site.register(User, UserAdmin)
custom_admin_site.register(LineaProduccion, LineaProduccionAdmin)
custom_admin_site.register(Sector, SectorAdmin)
custom_admin_site.register(Equipo, EquipoAdmin)
custom_admin_site.register(Deposito, DepositoAdmin)
custom_admin_site.register(Motor, MotorAdmin)
custom_admin_site.register(Variador, VariadorAdmin)
custom_admin_site.register(Proveedor, ProveedorAdmin)
custom_admin_site.register(Reparacion, ReparacionAdmin)
custom_admin_site.register(OrdenMantenimiento, OrdenMantenimientoAdmin)
custom_admin_site.register(HistorialMantenimiento, HistorialMantenimientoAdmin)
custom_admin_site.register(Evento, EventoAdmin)
custom_admin_site.register(RutaInspeccion, RutaInspeccionAdmin)
custom_admin_site.register(VariableInspeccion, VariableInspeccionAdmin)
custom_admin_site.register(InspeccionEjecucion, InspeccionEjecucionAdmin)
custom_admin_site.register(ResultadoInspeccion, ResultadoInspeccionAdmin)
custom_admin_site.register(HistorialCambioOrden, HistorialCambioOrdenAdmin)
custom_admin_site.register(PLC, PLCAdmin)
custom_admin_site.register(PLCEntradaSalida, PLCEntradaSalidaAdmin)
custom_admin_site.register(PLCLog, PLCLogAdmin)
custom_admin_site.register(NotificacionApp, NotificacionAppAdmin)
custom_admin_site.register(DispositivoApp, DispositivoAppAdmin)
custom_admin_site.register(ReunionDiaria, ReunionDiariaAdmin)
custom_admin_site.register(IncidenciaReunion, IncidenciaReunionAdmin)
custom_admin_site.register(PlanificacionReunion, PlanificacionReunionAdmin)
custom_admin_site.register(AccionReunion, AccionReunionAdmin)
custom_admin_site.register(Turno, TurnoAdmin)
custom_admin_site.register(Produccion, ProduccionAdmin)
custom_admin_site.register(ProduccionTurno, ProduccionTurnoAdmin)
custom_admin_site.register(FallaTurno, FallaTurnoAdmin)
custom_admin_site.register(ParadaTurno, ParadaTurnoAdmin)
custom_admin_site.register(NodeRedLog, NodeRedLogAdmin)